CREATE TABLE Roles
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_enum VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Users
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  varchar(50) NOT NULL UNIQUE,
    password  varchar(12) NOT NULL,
    role_Id   bigint      not null,
    is_active boolean DEFAULT TRUE
);

ALTER TABLE Users
    ADD FOREIGN KEY (role_Id) REFERENCES Roles (id);

INSERT INTO Roles(role_enum) VALUES ('ROLE_VIEWER');
INSERT INTO Roles(role_enum) VALUES ('ROLE_ADMIN');

CREATE TABLE Forms
(

    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name varchar(50)   NOT NULL,
    t_number    varchar(50)   not null,
    description varchar(2000) not null,
    status      varchar(10)   not null

);

